### ISSUE TITLE
npm run build的时候报错

### ISSUE THREAD

**Issue by haojian20161987** [PeakTai/vue-html5-editor#67]
(46): src/util/mixin.js
'default' is not exported by node_modules\._lrz@4.9.40@lrz\dist\lrz.all.bundle.js (imported by src\modules\image\dashboard.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
Error: 'default' is not exported by node_modules\._lrz@4.9.40@lrz\dist\lrz.all.bundle.js (imported by src\modules\image\dashboard.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
    at error (J:\webcode\vue-editor\vue-html5-editor\node_modules\._rollup@0.37.2@rollup\src\utils\error.js:2:14)
    at Module.trace (J:\webcode\vue-editor\vue-html5-editor\node_modules\._rollup@0.37.2@rollup\src\Module.js:364:4)
    at ModuleScope.findDeclaration (J:\webcode\vue-editor\vue-html5-editor\node_modules\._rollup@0.37.2@rollup\src\ast\scopes\ModuleScope.js:47:22)
    at Scope.findDeclaration (J:\webcode\vue-editor\vue-html5-editor\node_modules\._rollup@0.37.2@rollup\src\ast\scopes\Scope.js:90:39)
    at Scope.findDeclaration (J:\webcode\vue-editor\vue-html5-editor\node_modules\._rollup@0.37.2@rollup\src\ast\scopes\Scope.js:90:39)
    at CallExpression.bind (J:\webcode\vue-editor\vue-html5-editor\node_modules\._rollup@0.37.2@rollup\src\ast\nodes\CallExpression.js:10:30)
    at J:\webcode\vue-editor\vue-html5-editor\node_modules\._rollup@0.37.2@rollup\src\ast\Node.js:6:34
    at MemberExpression.eachChild (J:\webcode\vue-editor\vue-html5-editor\node_modules\._rollup@0.37.2@rollup\src\ast\Node.js:21:5)
    at MemberExpression.bind (J:\webcode\vue-editor\vue-html5-editor\node_modules\._rollup@0.37.2@rollup\src\ast\Node.js:6:8)
    at MemberExpression.bind (J:\webcode\vue-editor\vue-html5-editor\node_modules\._rollup@0.37.2@rollup\src\ast\nodes\MemberExpression.js:59:14)
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki

**Comment by PeakTai** [comment]
请问你用的nodejs是什么版本？另外在执行`npm install`的时候有没有报错？

**Comment by haojian20161987** [comment]
*******
C:\Users\hao>node -v
v6.10.1
*******
J:\webcode\vue-editor\vue-html5-editor>npm install

J:\webcode\vue-editor\vue-html5-editor>
********
如上：我的nodejs版本是v6.10.1。npm install，我先运行的cnpm install，使用淘宝的镜像安装的，然后再运行npm install也没有错误。
我运行cnpm run build和rollup -c报的错误一样，都是mixin模块没有export出来。我按照cmd给出的提示 https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module，我看了Custom named exports，换了写法
还是提示错误，

**Comment by luffyzhao** [comment]
@haojian20161987  我也遇到了一样的问题，你的解决了没？
